#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Manual verification script for bounding box display vs output behavior.

This script demonstrates the new behavior where:
1. Display frame (UI) ALWAYS shows bounding boxes
2. Output frame (downstream) respects the checkbox setting

To run this verification:
1. Start CV_Studio application
2. Create a workflow: Camera/Video → Object Detection → Display/Tracking
3. Check the Object Detection node display (should always show bboxes)
4. Toggle the "Draw Bounding Boxes" checkbox:
   - CHECKED: Output includes bounding boxes (for video recording)
   - UNCHECKED: Output is clean (for tracking)
5. Verify that UI always shows bboxes regardless of checkbox state
"""

import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def print_verification_guide():
    """Print a guide for manual verification of the fix"""
    
    print("=" * 80)
    print("MANUAL VERIFICATION GUIDE")
    print("Bounding Box Display vs Output Image Fix")
    print("=" * 80)
    print()
    print("OBJECTIVE:")
    print("Verify that the displayed image and output image are now separate:")
    print("- Display (UI): ALWAYS shows bounding boxes")
    print("- Output (downstream): Respects checkbox setting")
    print()
    print("=" * 80)
    print("STEP 1: Create Test Workflow")
    print("=" * 80)
    print()
    print("1. Start CV_Studio application")
    print("2. Create workflow: [Camera/Video Input] → [Object Detection] → [Display/Video]")
    print("3. Configure Object Detection node:")
    print("   - Select a model (e.g., YOLOX-Nano)")
    print("   - Set score threshold (e.g., 0.3)")
    print("4. Start the workflow")
    print()
    print("=" * 80)
    print("STEP 2: Verify Display Always Shows Bounding Boxes")
    print("=" * 80)
    print()
    print("1. Look at the Object Detection node's image preview")
    print("2. You should see bounding boxes with labels and scores")
    print("3. Note the checkbox: ☑ Draw Bounding Boxes (checked by default)")
    print()
    print("Expected: ✓ UI shows bounding boxes")
    print()
    print("=" * 80)
    print("STEP 3: Test CHECKED State (For Video Recording)")
    print("=" * 80)
    print()
    print("With checkbox CHECKED (☑):")
    print()
    print("1. Object Detection node display shows: Bounding boxes ✓")
    print("2. Downstream node (Display/Video) shows: Bounding boxes ✓")
    print("3. If saving video: Video includes bounding boxes ✓")
    print()
    print("Expected behavior:")
    print("  - Display frame: Has bounding boxes ✓")
    print("  - Output frame: Has bounding boxes ✓")
    print("  - Use case: Video recording with annotations")
    print()
    print("=" * 80)
    print("STEP 4: Test UNCHECKED State (For Tracking)")
    print("=" * 80)
    print()
    print("1. UNCHECK the 'Draw Bounding Boxes' checkbox: ☐")
    print()
    print("Expected changes:")
    print("  - Display frame: STILL shows bounding boxes ✓ (this is KEY!)")
    print("  - Output frame: Clean image, NO bounding boxes ✓")
    print()
    print("Verification:")
    print("1. Object Detection node display: Should STILL show bounding boxes")
    print("   (This is the fix - display is independent of output)")
    print("2. Downstream node: Should show clean image without bounding boxes")
    print("3. If connected to Tracking: Tracker receives clean frames")
    print("4. If saving video: Video has NO bounding boxes")
    print()
    print("Use case: Clean frames for tracking or clean video recording")
    print()
    print("=" * 80)
    print("STEP 5: Test with Tracking Node")
    print("=" * 80)
    print()
    print("1. Add workflow: [Object Detection] → [Tracking (MOT)] → [Display]")
    print("2. Uncheck 'Draw Bounding Boxes' on Object Detection")
    print()
    print("Expected:")
    print("  - Object Detection display: Shows detection bboxes ✓")
    print("  - Object Detection output: Clean image (no detection bboxes)")
    print("  - Tracking node receives: Clean image + detection JSON data")
    print("  - Tracking node draws: Its own tracking bboxes with TID")
    print("  - Final output: Only tracking bboxes visible")
    print()
    print("This allows:")
    print("  - Visual verification of detections in Object Detection node")
    print("  - Clean input for tracking (no bbox artifacts)")
    print("  - Tracking adds its own bboxes with track IDs")
    print()
    print("=" * 80)
    print("VERIFICATION CHECKLIST")
    print("=" * 80)
    print()
    print("☐ 1. With checkbox CHECKED:")
    print("     - Object Detection display shows bboxes")
    print("     - Output/downstream nodes show bboxes")
    print()
    print("☐ 2. With checkbox UNCHECKED:")
    print("     - Object Detection display STILL shows bboxes (KEY!)")
    print("     - Output/downstream nodes show clean image")
    print()
    print("☐ 3. With Tracking pipeline:")
    print("     - Object Detection shows detection bboxes")
    print("     - Tracking receives clean image")
    print("     - Tracking shows only tracking bboxes")
    print()
    print("☐ 4. JSON data always available regardless of checkbox")
    print()
    print("=" * 80)
    print("SUMMARY OF THE FIX")
    print("=" * 80)
    print()
    print("BEFORE the fix:")
    print("  - Checkbox controlled both display AND output simultaneously")
    print("  - Unchecked = No bboxes in display OR output")
    print()
    print("AFTER the fix:")
    print("  - Display frame: ALWAYS shows bboxes (for user feedback)")
    print("  - Output frame: Respects checkbox (for downstream processing)")
    print("  - Unchecked = Bboxes in display, clean output")
    print()
    print("Benefits:")
    print("  ✓ Always see what detector found (debugging/verification)")
    print("  ✓ Send clean images when needed (tracking/recording)")
    print("  ✓ More flexible workflow control")
    print()
    print("=" * 80)
    print()


if __name__ == '__main__':
    print_verification_guide()
