"""
Project scaffolding generator.

Creates production-ready project structure including:
  - Dockerfile (NVIDIA DeepStream base image)
  - Makefile
  - docker-compose.yml
  - run.sh
  - README.md
  - models/ directory
  - output/ directory
"""

from __future__ import annotations

from pathlib import Path

from tools.deepstream_engine.pipeline_builder import DeepStreamPipeline


def generate_scaffold(pipeline: DeepStreamPipeline, output_dir: str | Path) -> list[str]:
    """Generate all scaffolding files for the DeepStream project."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    generated = []

    generated.append(_write_dockerfile(pipeline, output_dir))
    generated.append(_write_docker_compose(pipeline, output_dir))
    generated.append(_write_makefile(pipeline, output_dir))
    generated.append(_write_run_script(pipeline, output_dir))
    generated.append(_write_readme(pipeline, output_dir))
    generated.append(_write_gitignore(output_dir))
    generated.append(_write_convert_models_script(pipeline, output_dir))

    # Create directories
    (output_dir / "models").mkdir(exist_ok=True)
    (output_dir / "output").mkdir(exist_ok=True)
    (output_dir / "tracker").mkdir(exist_ok=True)

    return generated


def _write_dockerfile(pipeline: DeepStreamPipeline, output_dir: Path) -> str:
    """Generate optimized Dockerfile for RTX 5070."""
    content = f"""# ==============================================================================
# DeepStream Production Dockerfile
# Generated by CvStudio DeepStream Engine
# Target: {pipeline.profile.name} ({pipeline.profile.vram_gb}GB VRAM, {pipeline.profile.system_ram_gb}GB RAM)
# ==============================================================================

FROM nvcr.io/nvidia/deepstream:7.1-triton-multiarch

# Environment
ENV DEBIAN_FRONTEND=noninteractive
ENV CUDA_MODULE_LOADING=LAZY
ENV DS_CONFIG_PATH=/app/deepstream_app_config.txt

WORKDIR /app

# Install additional dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    python3-pip \\
    python3-dev \\
    libgstreamer1.0-dev \\
    libgstreamer-plugins-base1.0-dev \\
    && rm -rf /var/lib/apt/lists/*

# Install Python bindings
RUN pip3 install --no-cache-dir \\
    pyds \\
    paho-mqtt \\
    pymongo

# Copy configuration files
COPY deepstream_app_config.txt .
COPY config_*.txt ./
COPY tracker/ ./tracker/
COPY labels.txt ./
COPY msg_conv_config.txt* ./

# Copy models (ONNX files to be converted to TensorRT on first run)
COPY models/ ./models/

# Copy custom parser libraries
COPY libs/ ./libs/ 2>/dev/null || true

# Output directory
RUN mkdir -p /app/output

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \\
    CMD pgrep -f deepstream-app || exit 1

# TensorRT engine cache (persist across container restarts)
VOLUME ["/app/models"]
VOLUME ["/app/output"]

# Entry point
ENTRYPOINT ["deepstream-app"]
CMD ["-c", "deepstream_app_config.txt"]
"""
    path = output_dir / "Dockerfile"
    path.write_text(content, encoding="utf-8")
    return "Dockerfile"


def _write_docker_compose(pipeline: DeepStreamPipeline, output_dir: Path) -> str:
    """Generate docker-compose.yml."""
    num_sources = max(len(pipeline.sources), 1)

    content = f"""# ==============================================================================
# Docker Compose - DeepStream Production Deployment
# Generated by CvStudio DeepStream Engine
# Target: {pipeline.profile.name}
# ==============================================================================

version: '3.8'

services:
  deepstream:
    build: .
    image: cvstudio-deepstream:{pipeline.name}
    container_name: {pipeline.name}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CUDA_MODULE_LOADING=LAZY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, video, compute, utility]
        limits:
          memory: {pipeline.profile.system_ram_gb}G
    volumes:
      - ./models:/app/models
      - ./output:/app/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    ipc: host
    shm_size: '4gb'
    restart: unless-stopped
    # GPU memory optimization
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
"""
    path = output_dir / "docker-compose.yml"
    path.write_text(content, encoding="utf-8")
    return "docker-compose.yml"


def _write_makefile(pipeline: DeepStreamPipeline, output_dir: Path) -> str:
    """Generate Makefile."""
    content = f"""# ==============================================================================
# Makefile - DeepStream Production Project
# Generated by CvStudio DeepStream Engine
# Target: {pipeline.profile.name}
# ==============================================================================

.PHONY: build run stop logs convert-models clean test

PROJECT_NAME := {pipeline.name}
DOCKER_IMAGE := cvstudio-deepstream:$(PROJECT_NAME)

# Build the Docker image
build:
\tdocker compose build

# Run the DeepStream pipeline
run:
\tdocker compose up -d
\t@echo "Pipeline started. Use 'make logs' to view output."

# Run interactively (foreground)
run-interactive:
\tdocker compose up

# Stop the pipeline
stop:
\tdocker compose down

# View logs
logs:
\tdocker compose logs -f

# Convert ONNX models to TensorRT engines
convert-models:
\t./convert_models.sh

# Run directly without Docker (requires DeepStream SDK installed)
run-native:
\tdeepstream-app -c deepstream_app_config.txt

# Performance profiling
profile:
\tnsys profile --stats=true --force-overwrite=true -o profile_$(PROJECT_NAME) \\
\t\tdeepstream-app -c deepstream_app_config.txt

# Clean generated engines and output
clean:
\trm -f models/*.engine
\trm -f output/*
\trm -f profile_*

# Validate configuration
test:
\t@echo "Validating DeepStream configuration..."
\t@test -f deepstream_app_config.txt && echo "[OK] Main config exists" || echo "[FAIL] Missing main config"
\t@test -f config_pgie.txt && echo "[OK] PGIE config exists" || echo "[WARN] No PGIE config"
\t@test -d models && echo "[OK] Models directory exists" || echo "[FAIL] Missing models directory"
\t@echo "Validation complete."
"""
    path = output_dir / "Makefile"
    path.write_text(content, encoding="utf-8")
    return "Makefile"


def _write_run_script(pipeline: DeepStreamPipeline, output_dir: Path) -> str:
    """Generate run.sh launcher script."""
    content = f"""#!/bin/bash
# ==============================================================================
# DeepStream Pipeline Launcher
# Generated by CvStudio DeepStream Engine
# Target: {pipeline.profile.name} ({pipeline.profile.vram_gb}GB VRAM)
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
cd "$SCRIPT_DIR"

# GPU Memory Optimization for {pipeline.profile.name}
export CUDA_MODULE_LOADING=LAZY
export TRT_ENGINE_CACHE_ENABLE=1

# Check NVIDIA driver
if ! nvidia-smi &>/dev/null; then
    echo "[ERROR] NVIDIA driver not found. Please install NVIDIA drivers."
    exit 1
fi

echo "=============================================="
echo " CvStudio DeepStream Pipeline"
echo " Project: {pipeline.name}"
echo " Target GPU: {pipeline.profile.name}"
echo " VRAM: {pipeline.profile.vram_gb} GB"
echo " RAM: {pipeline.profile.system_ram_gb} GB"
echo " FP16: {'Enabled' if pipeline.profile.fp16_enabled else 'Disabled'}"
echo " Batch Size: {pipeline.profile.max_batch_size}"
echo "=============================================="
echo ""

# Check if models need TensorRT conversion
NEEDS_CONVERSION=false
for onnx_file in models/*.onnx; do
    if [ -f "$onnx_file" ]; then
        engine_file="${{onnx_file%.onnx}}.engine"
        if [ ! -f "$engine_file" ]; then
            NEEDS_CONVERSION=true
            break
        fi
    fi
done

if [ "$NEEDS_CONVERSION" = true ]; then
    echo "[INFO] TensorRT engines not found. They will be generated on first run."
    echo "[INFO] This may take several minutes depending on model complexity."
    echo ""
fi

# Launch DeepStream
echo "[INFO] Starting DeepStream pipeline..."
exec deepstream-app -c deepstream_app_config.txt "$@"
"""
    path = output_dir / "run.sh"
    path.write_text(content, encoding="utf-8")
    path.chmod(0o755)
    return "run.sh"


def _write_readme(pipeline: DeepStreamPipeline, output_dir: Path) -> str:
    """Generate project README."""
    sources_info = "\n".join(
        f"  - Source {s.source_id}: {s.source_type} ({s.uri or s.device or 'N/A'})"
        for s in pipeline.sources
    ) or "  - No sources configured (add source URIs to config)"

    infer_info = ""
    if pipeline.primary_gie:
        infer_info += f"  - **PGIE**: {pipeline.primary_gie.model_name} ({pipeline.primary_gie.input_width}x{pipeline.primary_gie.input_height})\n"
    for i, sgie in enumerate(pipeline.secondary_gies):
        infer_info += f"  - **SGIE {i}**: {sgie.model_name} ({sgie.node_tag})\n"
    if not infer_info:
        infer_info = "  - No inference configured\n"

    tracker_info = f"  - {pipeline.tracker.tracker_name}" if pipeline.tracker else "  - None"

    content = f"""# {pipeline.name}

> Production-ready DeepStream pipeline generated from CvStudio project.
> Optimized for **{pipeline.profile.name}** ({pipeline.profile.vram_gb} GB VRAM, {pipeline.profile.system_ram_gb} GB RAM).

## Pipeline Architecture

```
Sources → StreamMux → PGIE → Tracker → SGIE(s) → OSD → Tiler → Sinks
```

### Sources
{sources_info}

### Inference
{infer_info}
### Tracker
{tracker_info}

### Sinks
{chr(10).join(f'  - Sink {s.sink_id}: {s.sink_type}' for s in pipeline.sinks)}

## Quick Start

### With Docker (Recommended)

```bash
# Build the container
make build

# Run the pipeline
make run

# View logs
make logs

# Stop
make stop
```

### Without Docker

Requires NVIDIA DeepStream SDK 7.1+ installed.

```bash
# Copy your ONNX models to models/
cp /path/to/your/model.onnx models/

# Run directly
make run-native
# OR
./run.sh
```

## Model Setup

1. Place your ONNX model files in the `models/` directory
2. TensorRT engines (`.engine`) will be auto-generated on first run
3. Engine generation takes 2-10 minutes per model (cached afterward)

### Model Conversion (Manual)

```bash
# Convert all ONNX models to TensorRT FP16 engines
./convert_models.sh
```

## Performance Tuning

This project is optimized for **{pipeline.profile.name}**:

| Parameter | Value |
|-----------|-------|
| GPU Architecture | {pipeline.profile.gpu_arch} |
| TensorRT Precision | {'FP16' if pipeline.profile.fp16_enabled else 'FP32'} |
| Max Batch Size | {pipeline.profile.max_batch_size} |
| TRT Workspace | {pipeline.profile.tensorrt_workspace_mb} MB |
| CUDA Streams | {pipeline.profile.num_cuda_streams} |
| Max Streams | {pipeline.profile.max_simultaneous_streams} |

## File Structure

```
{pipeline.name}/
├── deepstream_app_config.txt   # Main pipeline configuration
├── config_pgie.txt             # Primary inference config
├── config_sgie_*.txt           # Secondary inference configs
├── tracker/                    # Tracker configuration
├── models/                     # ONNX models & TensorRT engines
├── output/                     # Output files (recordings, etc.)
├── labels.txt                  # Class labels
├── Dockerfile                  # Production container
├── docker-compose.yml          # Orchestration
├── Makefile                    # Build/run commands
├── run.sh                      # Native launcher
└── convert_models.sh           # Model conversion script
```

## Troubleshooting

- **First run is slow**: TensorRT engine compilation (one-time cost)
- **Out of memory**: Reduce `batch-size` in config files or use INT8
- **No display**: Set `type=1` (fake sink) in sink config for headless mode
- **RTSP timeout**: Increase `latency` in source config

## Generated By

CvStudio DeepStream Engine v1.0.0
"""
    path = output_dir / "README.md"
    path.write_text(content, encoding="utf-8")
    return "README.md"


def _write_gitignore(output_dir: Path) -> str:
    """Generate .gitignore."""
    content = """# TensorRT engine files (platform-specific, regenerated on first run)
*.engine

# Output files
output/

# Profile data
profile_*
*.nsys-rep
*.qdrep

# Python
__pycache__/
*.pyc

# OS
.DS_Store
Thumbs.db
"""
    path = output_dir / ".gitignore"
    path.write_text(content, encoding="utf-8")
    return ".gitignore"


def _write_convert_models_script(pipeline: DeepStreamPipeline, output_dir: Path) -> str:
    """Generate model conversion script."""
    precision_flag = "--fp16" if pipeline.profile.fp16_enabled else ""
    if pipeline.profile.int8_enabled:
        precision_flag = "--int8"

    content = f"""#!/bin/bash
# ==============================================================================
# ONNX to TensorRT Model Conversion Script
# Generated by CvStudio DeepStream Engine
# Target: {pipeline.profile.name}
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
MODELS_DIR="$SCRIPT_DIR/models"
WORKSPACE_SIZE={pipeline.profile.tensorrt_workspace_mb}

echo "=============================================="
echo " TensorRT Model Conversion"
echo " Target: {pipeline.profile.name}"
echo " Precision: {'FP16' if pipeline.profile.fp16_enabled else 'INT8' if pipeline.profile.int8_enabled else 'FP32'}"
echo " Workspace: ${{WORKSPACE_SIZE}} MB"
echo "=============================================="
echo ""

if ! command -v trtexec &>/dev/null; then
    echo "[ERROR] trtexec not found. Please install TensorRT."
    echo "        Usually located at /usr/src/tensorrt/bin/trtexec"
    exit 1
fi

CONVERTED=0
FAILED=0

for onnx_file in "$MODELS_DIR"/*.onnx; do
    if [ ! -f "$onnx_file" ]; then
        echo "[INFO] No ONNX files found in $MODELS_DIR"
        exit 0
    fi

    engine_file="${{onnx_file%.onnx}}.engine"
    model_name=$(basename "$onnx_file")

    if [ -f "$engine_file" ]; then
        echo "[SKIP] $model_name (engine already exists)"
        continue
    fi

    echo "[CONVERTING] $model_name ..."
    echo "  Input: $onnx_file"
    echo "  Output: $engine_file"

    if trtexec \\
        --onnx="$onnx_file" \\
        --saveEngine="$engine_file" \\
        {precision_flag} \\
        --workspace=$WORKSPACE_SIZE \\
        --minShapes=input:1x3x{pipeline.profile.max_batch_size // 2}x{pipeline.profile.max_batch_size // 2} \\
        --optShapes=input:1x3x640x640 \\
        --maxShapes=input:{pipeline.profile.max_batch_size}x3x1280x1280 \\
        --verbose 2>&1 | tee "/tmp/trtexec_$model_name.log"; then
        echo "[OK] $model_name converted successfully"
        CONVERTED=$((CONVERTED + 1))
    else
        echo "[FAIL] $model_name conversion failed. Check /tmp/trtexec_$model_name.log"
        FAILED=$((FAILED + 1))
    fi
    echo ""
done

echo "=============================================="
echo " Conversion Complete"
echo " Converted: $CONVERTED"
echo " Failed: $FAILED"
echo "=============================================="
"""
    path = output_dir / "convert_models.sh"
    path.write_text(content, encoding="utf-8")
    path.chmod(0o755)
    return "convert_models.sh"
