# -*- coding: utf-8 -*-
"""
NanoDetLite — Production-Ready Object Detector
==============================================
Backbone léger + tête single-scale, entraîné sur COCO.

Améliorations production :
  - Config dataclass validée
  - Seed globale pour reproductibilité
  - Box encoding pure sigmoid (symétrique train / decode, sans exp)
  - Checkpointing (save + resume)
  - Validation loop
  - Module mAP complet : compute_map_50, compute_precision_recall, per_class_AP
  - Logging structuré (fichier + console + TensorBoard optionnel)
  - Clipping de gradient
  - LR scheduler cosine
  - Export ONNX avec vérification onnxruntime
  - Gestion d'erreurs complète
"""



# -*- coding: utf-8 -*-
"""create_onnx_Nanodet_LAMAAZ_1M.ipynb

Automatically generated by Colab.
"""

# ============================================================
# 🚀 IMPORTS & INSTALLATIONS
# ============================================================
import os
import time
import json
import zipfile
import requests
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torchvision.datasets import CocoDetection
from torch.utils.data import DataLoader
from tqdm.auto import tqdm



# =========================
# 🚀 COCO PRO PIPELINE (AUTO FIX CACHE CORRUPT)
# =========================

import os
import time
import json
import zipfile
import requests

DATA_DIR = "coco"
os.makedirs(DATA_DIR, exist_ok=True)

FILES = {
    "train2017.zip": "http://images.cocodataset.org/zips/train2017.zip",
    "annotations.zip": "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
}

# =========================
# 💣 FORCE CLEAN CORRUPTED FILES
# =========================
def safe_remove(path):
    if os.path.exists(path):
        print(f"🧹 removing: {path}")
        os.remove(path)

# =========================
# 🔥 ROBUST DOWNLOAD (ALWAYS OVERWRITE IF CORRUPT)
# =========================
def download_file(url, path, retries=5):
    for i in range(retries):

        try:
            print(f"⬇️ downloading ({i+1}/{retries}) {path}")

            with requests.get(url, stream=True, timeout=60) as r:
                r.raise_for_status()

                total = int(r.headers.get("content-length", 0))
                downloaded = 0

                with open(path, "wb") as f:
                    for chunk in r.iter_content(chunk_size=1024 * 1024):
                        if chunk:
                            f.write(chunk)
                            downloaded += len(chunk)

            # sanity check
            if total > 0 and downloaded < total * 0.95:
                raise Exception("Incomplete download")

            print(f"✔ downloaded: {path}")
            return

        except Exception as e:
            print(f"❌ error: {e}")
            time.sleep(2)

    raise RuntimeError(f"Failed: {path}")

# =========================
# 🧪 VALIDATE ZIP (STRICT)
# =========================
def validate_zip(path):
    try:
        if not zipfile.is_zipfile(path):
            raise Exception("Not a zip file")

        with zipfile.ZipFile(path, "r") as z:
            bad = z.testzip()
            if bad:
                raise Exception(f"Corrupt inside zip: {bad}")

        print(f"✔ ZIP OK: {path}")
        return True

    except Exception as e:
        print(f"❌ ZIP INVALID: {path} -> {e}")
        return False

# =========================
# 🚀 MAIN DOWNLOAD LOGIC (CACHE SAFE)
# =========================
for name, url in FILES.items():

    path = name

    # 🔥 if file exists, validate it
    if os.path.exists(path):

        print(f"🔍 checking cache: {path}")

        if not validate_zip(path):
            safe_remove(path)   # 💣 remove corrupted cache
        else:
            print(f"✔ valid cache: {path}")
            continue

    # ⬇️ re-download if missing or corrupted
    download_file(url, path)

    # 🔁 validate again after download
    if not validate_zip(path):
        safe_remove(path)
        raise RuntimeError(f"Download failed permanently: {path}")

# =========================
# 📦 SAFE EXTRACT (IDEMPOTENT)
# =========================
def safe_extract(zip_path, out_dir):
    marker = os.path.join(out_dir, f".extracted_{zip_path}")

    if os.path.exists(marker):
        print(f"✔ already extracted: {zip_path}")
        return

    print(f"📦 extracting {zip_path}...")

    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall(out_dir)

    open(marker, "w").close()

    print(f"✔ extracted: {zip_path}")

safe_extract("train2017.zip", DATA_DIR)
safe_extract("annotations.zip", DATA_DIR)

# =========================
# 🧪 JSON CHECK
# =========================
json_path = os.path.join(DATA_DIR, "annotations", "instances_train2017.json")

with open(json_path, "r") as f:
    data = json.load(f)

print("✔ COCO READY")
print("images:", len(data["images"]))
print("annotations:", len(data["annotations"]))







import os

# =========================
# CONFIG DATASET COCO
# =========================

DATA_DIR = "coco"

IMG_DIR = os.path.join(DATA_DIR, "train2017")
ANN_PATH = os.path.join(DATA_DIR, "annotations", "instances_train2017.json")

IMG_SIZE = 320
NUM_CLASSES = 80
BATCH_SIZE = 8

from torchvision.datasets import CocoDetection
from torch.utils.data import DataLoader
import torchvision

# ============================================================
# DATASET
# ============================================================



transform = torchvision.transforms.Compose([
    torchvision.transforms.Resize((IMG_SIZE, IMG_SIZE)),
    torchvision.transforms.ToTensor()
])

dataset = CocoDetection(
    root=IMG_DIR,
    annFile=ANN_PATH,
    transform=transform
)

def collate_fn(batch):
    imgs, targets = zip(*batch)
    return torch.stack(imgs), targets

loader = DataLoader(
    dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_fn,
    num_workers=2,
    pin_memory=True
)
























# ============================================================
# CONFIGURATION GENERALE
# ============================================================
CFG = {
    "img_size": 320,
    "num_classes": 80,
    "batch_size": 8,
    "epochs": 1,
    "max_steps": 200,
    "lr": 1e-4
}

DATA_DIR = "coco"
IMG_DIR = os.path.join(DATA_DIR, "train2017")
ANN_PATH = os.path.join(DATA_DIR, "annotations", "instances_train2017.json")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
IMG_SIZE = CFG["img_size"]
NUM_CLASSES = CFG["num_classes"]

os.makedirs(DATA_DIR, exist_ok=True)

# ============================================================
# ⬇️ PIPELINE TELECHARGEMENT COCO (CACHE SAFE)
# ============================================================
FILES = {
    "train2017.zip": "http://images.cocodataset.org/zips/train2017.zip",
    "annotations.zip": "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
}

def safe_remove(path):
    if os.path.exists(path):
        print(f"🧹 Removing corrupted file: {path}")
        os.remove(path)

def download_file(url, path, retries=5):
    for i in range(retries):
        try:
            print(f"⬇️ Downloading ({i+1}/{retries}) {path}")
            with requests.get(url, stream=True, timeout=60) as r:
                r.raise_for_status()
                total = int(r.headers.get("content-length", 0))
                downloaded = 0
                with open(path, "wb") as f:
                    for chunk in r.iter_content(chunk_size=1024 * 1024):
                        if chunk:
                            f.write(chunk)
                            downloaded += len(chunk)
            if total > 0 and downloaded < total * 0.95:
                raise Exception("Incomplete download")
            print(f"✔ Downloaded: {path}")
            return
        except Exception as e:
            print(f"❌ Error: {e}")
            time.sleep(2)
    raise RuntimeError(f"Failed to download: {path}")

def validate_zip(path):
    try:
        if not zipfile.is_zipfile(path):
            raise Exception("Not a valid zip archive")
        with zipfile.ZipFile(path, "r") as z:
            if z.testzip() is not None:
                raise Exception("Corrupt archive intern structure")
        print(f"✔ ZIP OK: {path}")
        return True
    except Exception as e:
        print(f"❌ ZIP INVALID: {path} -> {e}")
        return False

for name, url in FILES.items():
    if os.path.exists(name):
        print(f"🔍 Checking cache: {name}")
        if not validate_zip(name):
            safe_remove(name)
        else:
            continue
    download_file(url, name)
    if not validate_zip(name):
        safe_remove(name)
        raise RuntimeError(f"Download permanently corrupted: {name}")

def safe_extract(zip_path, out_dir):
    marker = os.path.join(out_dir, f".extracted_{zip_path}")
    if os.path.exists(marker):
        print(f"✔ Already extracted: {zip_path}")
        return
    print(f"📦 Extracting {zip_path}...")
    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall(out_dir)
    open(marker, "w").close()
    print(f"✔ Extracted: {zip_path}")

safe_extract("train2017.zip", DATA_DIR)
safe_extract("annotations.zip", DATA_DIR)

# Validation JSON COCO
with open(ANN_PATH, "r") as f:
    coco_data = json.load(f)
print(f"✔ COCO READY | Images: {len(coco_data['images'])} | Annotations: {len(coco_data['annotations'])}")

# MAPPING DES CLASSES COCO (1-91 ID non-continus -> 0-79 index continus)
coco_ids = sorted([cat['id'] for cat in coco_data['categories']])
coco_label_map = {old_id: new_id for new_id, old_id in enumerate(coco_ids)}



def collate_fn_pipeline(batch):
    imgs, targets = zip(*batch)
    stacked_imgs = torch.stack(imgs)
    
    # 320 / 16 (4 strides de taille 2 du backbone) = 20
    H_out, W_out = IMG_SIZE // 16, IMG_SIZE // 16 
    
    cls_t, obj_t, box_t = build_targets_cpu(
        targets, len(batch), H_out, W_out, IMG_SIZE, NUM_CLASSES, coco_label_map
    )
    return stacked_imgs, cls_t, obj_t, box_t

# ============================================================
# DATALOADER
# ============================================================
transform = torchvision.transforms.Compose([
    torchvision.transforms.Resize((IMG_SIZE, IMG_SIZE)),
    torchvision.transforms.ToTensor()
])

dataset = CocoDetection(root=IMG_DIR, annFile=ANN_PATH, transform=transform)

loader = DataLoader(
    dataset,
    batch_size=CFG["batch_size"],
    shuffle=True,
    collate_fn=collate_fn_pipeline,
    num_workers=2,
    pin_memory=True,
    drop_last=True
)







from __future__ import annotations

import logging
import math
import os
import random
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as T
from torch.utils.data import DataLoader, random_split
from torchvision.datasets import CocoDetection
from torchvision.ops import nms, box_iou
from tqdm.auto import tqdm

# ============================================================
# LOGGING
# ============================================================
LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(LOG_DIR / "train.log", encoding="utf-8"),
    ],
)
log = logging.getLogger(__name__)

try:
    from torch.utils.tensorboard import SummaryWriter
    _TB_AVAILABLE = True
except ImportError:
    _TB_AVAILABLE = False
    log.warning("TensorBoard non disponible — pip install tensorboard pour l'activer.")


# ============================================================
# CONFIG
# ============================================================
@dataclass
class Config:
    # Données
    img_dir:   str   = "coco/train2017"
    ann_path:  str   = "coco/annotations/instances_train2017.json"
    img_size:  int   = 320
    num_classes: int = 80
    val_split: float = 0.05

    # Entraînement
    batch_size:  int            = 8
    epochs:      int            = 10
    max_steps:   Optional[int]  = None   # None = pas de limite (debug)
    lr:          float          = 1e-4
    weight_decay: float         = 1e-4
    grad_clip:   float          = 10.0
    seed:        int            = 42

    # Focal loss
    focal_alpha: float = 0.25
    focal_gamma: float = 2.0

    # Loss weights
    w_cls: float = 1.0
    w_obj: float = 1.0
    w_box: float = 5.0

    # Box encoding — pure sigmoid
    # xy  : sigmoid(pred) → offset ∈ (0,1) dans la cellule
    # wh  : sigmoid(pred) * wh_scale → taille relative à l'image
    # wh_scale règle la taille max prédictible (2.0 = 2× img_size max)
    wh_scale: float = 2.0

    # Checkpoint
    ckpt_dir:   str           = "checkpoints"
    save_every: int           = 1
    resume:     Optional[str] = None

    # Export
    onnx_path: str = "nanodet.onnx"
    opset:     int = 17

    # Inférence
    conf_threshold:    float = 0.4
    nms_iou_threshold: float = 0.5

    # mAP
    map_iou_threshold: float = 0.5   # IoU pour TP/FP

    # IDs COCO valides — fallback statique pour COCO complet (80 classes).
    # Si tu travailles sur un subset, laisse vide ([]) : le mapping sera
    # construit dynamiquement depuis les annotations au moment du chargement.
    coco_valid_ids: list = field(default_factory=lambda: [
        1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,
        31,32,33,34,35,36,37,38,39,40,41,42,43,44,46,47,48,49,50,51,52,53,54,
        55,56,57,58,59,60,61,62,63,64,65,67,70,72,73,74,75,76,77,78,79,80,81,
        82,84,85,86,87,88,89,90
    ])

    def __post_init__(self) -> None:
        assert 0 < self.val_split < 1,  "val_split doit être dans (0, 1)"
        assert self.img_size % 32 == 0, "img_size doit être divisible par 32"
        if self.coco_valid_ids:
            assert len(self.coco_valid_ids) == self.num_classes, (
                f"num_classes ({self.num_classes}) ≠ len(coco_valid_ids) "
                f"({len(self.coco_valid_ids)}). "
                "Laisse coco_valid_ids=[] pour un mapping dynamique."
            )

    @property
    def label_map(self) -> dict[int, int]:
        """Mapping category_id → index continu. Valide seulement si coco_valid_ids est renseigné."""
        return {old: i for i, old in enumerate(self.coco_valid_ids)}

    @property
    def device(self) -> torch.device:
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")

    @property
    def feature_size(self) -> int:
        return self.img_size // 16


CFG = Config()


# ============================================================
# REPRODUCTIBILITÉ
# ============================================================
def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# ============================================================
# MODÈLE
# ============================================================
class ConvBnRelu(nn.Sequential):
    def __init__(self, in_ch: int, out_ch: int, kernel: int = 3,
                 stride: int = 1, padding: int = 1) -> None:
        super().__init__(
            nn.Conv2d(in_ch, out_ch, kernel, stride, padding, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )


class Backbones(nn.Module):
    """4 convolutions stride-2 → stride global 16."""
    def __init__(self) -> None:
        super().__init__()
        self.net = nn.Sequential(
            ConvBnRelu(3,   16,  stride=2),
            ConvBnRelu(16,  32,  stride=2),
            ConvBnRelu(32,  64,  stride=2),
            ConvBnRelu(64, 128,  stride=2),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)

class DWConv(nn.Module):
    """Depthwise separable convolution block (MobileNet style)."""
    def __init__(self, in_ch: int, out_ch: int, stride: int = 1):
        super().__init__()

        self.depthwise = nn.Conv2d(
            in_ch, in_ch,
            kernel_size=3,
            stride=stride,
            padding=1,
            groups=in_ch,
            bias=False
        )

        self.pointwise = nn.Conv2d(
            in_ch, out_ch,
            kernel_size=1,
            stride=1,
            bias=False
        )

        self.bn = nn.BatchNorm2d(out_ch)
        self.act = nn.ReLU(inplace=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.depthwise(x)
        x = self.pointwise(x)
        x = self.bn(x)
        return self.act(x)


class Backbone(nn.Module):
    """
    Backbone lightweight type MobileNetV1-like :
    - depthwise separable convolutions
    - stride total = 16
    - plus robuste que Conv standard à taille égale
    """
    def __init__(self) -> None:
        super().__init__()

        self.net = nn.Sequential(
            DWConv(3,   16, stride=2),   # 320 -> 160
            DWConv(16,  32, stride=2),   # 160 -> 80
            DWConv(32,  64, stride=2),   # 80  -> 40
            DWConv(64, 128, stride=2),   # 40  -> 20
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)
class Head(nn.Module):
    """Tête single-scale : cls / objectness / box."""
    def __init__(self, num_classes: int) -> None:
        super().__init__()
        self.shared = nn.Conv2d(128, 128, 3, padding=1)
        self.cls    = nn.Conv2d(128, num_classes, 1)
        self.obj    = nn.Conv2d(128, 1, 1)
        self.box    = nn.Conv2d(128, 4, 1)
        self._init_biases(num_classes)

    def _init_biases(self, num_classes: int) -> None:
        prior_prob = 0.01
        bias_value = -math.log((1 - prior_prob) / prior_prob)
        nn.init.constant_(self.cls.bias, bias_value)
        nn.init.constant_(self.obj.bias, bias_value)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        x = F.relu(self.shared(x), inplace=True)
        return self.cls(x), self.obj(x), self.box(x)


class NanoDetLite(nn.Module):
    def __init__(self, num_classes: int = 80) -> None:
        super().__init__()
        self.backbone = Backbone()
        self.head     = Head(num_classes)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        return self.head(self.backbone(x))


def build_label_map_from_annotations(ann_path: str) -> tuple[dict[int, int], int]:
    """
    Construit dynamiquement le mapping category_id → index continu
    à partir du fichier d'annotations COCO.

    Garantit la stabilité du mapping quel que soit le subset utilisé,
    contrairement à un mapping hardcodé qui peut silencieusement dériver
    sur des subsets COCO personnalisés.

    Retourne (label_map, num_classes).
    """
    import json
    with open(ann_path, "r") as f:
        data = json.load(f)
    # Tri par id pour garantir un ordre déterministe
    cats = sorted(data["categories"], key=lambda c: c["id"])
    label_map = {c["id"]: i for i, c in enumerate(cats)}
    log.info(
        "Label map dynamique : %d classes (ids %d→%d)",
        len(label_map),
        cats[0]["id"],
        cats[-1]["id"],
    )
    return label_map, len(label_map)


# ============================================================
# Représentation stockée dans box_t :
#   [tx, ty] : offset de cellule ∈ [0, 1]   (= sigmoid de la sortie brute)
#   [tw, th] : taille relative à l'image ∈ [0, wh_scale]
#              (= sigmoid(raw) * wh_scale)
#
# Au décodage : même formule — pas de exp(), pas de mismatch.
# wh_scale=2.0 signifie qu'on peut prédire des boîtes allant jusqu'à
# 2× la taille de l'image, ce qui couvre tous les cas COCO.

def encode_box(cx_pixel: float, cy_pixel: float,
               w: float, h: float,
               ix: int, iy: int,
               stride: float, img_size: int,
               wh_scale: float) -> tuple[float, float, float, float]:
    """
    Encode une boîte en cibles pour sigmoid-only box head.
    Retourne (tx, ty, tw, th) directement stockés dans box_t.
    """
    gx = cx_pixel / stride
    gy = cy_pixel / stride
    tx = gx - ix                         # offset x ∈ [0, 1]
    ty = gy - iy                         # offset y ∈ [0, 1]
    tw = (w / img_size) / wh_scale       # ∈ [0, 1] pour sigmoid inverse
    th = (h / img_size) / wh_scale
    return tx, ty, tw, th


def decode_box(raw: torch.Tensor,
               grid_x: torch.Tensor,
               grid_y: torch.Tensor,
               stride: float,
               img_size: int,
               wh_scale: float) -> tuple[torch.Tensor, ...]:
    """
    Décode les sorties brutes box_p en coordonnées pixel absolues cx,cy,w,h.
    Tout est en sigmoid — aucun exp().
    """
    pred_cx = (torch.sigmoid(raw[:, 0]) + grid_x) * stride
    pred_cy = (torch.sigmoid(raw[:, 1]) + grid_y) * stride
    pred_w  = torch.sigmoid(raw[:, 2]) * wh_scale * img_size
    pred_h  = torch.sigmoid(raw[:, 3]) * wh_scale * img_size
    return pred_cx, pred_cy, pred_w, pred_h


# ============================================================
# CONSTRUCTION DES TARGETS — VECTORISÉE
# ============================================================
def build_targets(
    targets:    list[list[dict]],
    batch_size: int,
    H: int,
    W: int,
    cfg:        Config,
    label_map:  dict[int, int],
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Construit cls_t / obj_t / box_t de façon vectorisée par image.

    Au lieu d'une double boucle Python sur (batch × objets), on :
      1. collecte toutes les annotations valides en une passe légère
      2. empile en tenseurs et fait les calculs grille en une seule op

    Gain typique : ×3 à ×6 sur COCO batch-8, ×10+ sur batch-32+.
    """
    cls_t = torch.zeros((batch_size, cfg.num_classes, H, W))
    obj_t = torch.zeros((batch_size, 1, H, W))
    box_t = torch.zeros((batch_size, 4, H, W))
    stride = cfg.img_size / H

    for b, anns in enumerate(targets):
        # ---- Collecte des annotations valides pour cette image ----
        cls_ids, cxs, cys, ws, hs = [], [], [], [], []
        for ann in anns:
            if "bbox" not in ann or "category_id" not in ann:
                continue
            raw_id = ann["category_id"]
            if raw_id not in label_map:
                continue
            x, y, w, h = ann["bbox"]
            if w < 2 or h < 2:
                continue
            cls_ids.append(label_map[raw_id])
            cxs.append(x + w / 2)
            cys.append(y + h / 2)
            ws.append(w)
            hs.append(h)

        if not cls_ids:
            continue

        # ---- Calculs vectorisés ----
        cls_t_img = torch.tensor(cls_ids, dtype=torch.long)
        cx  = torch.tensor(cxs,  dtype=torch.float32)
        cy  = torch.tensor(cys,  dtype=torch.float32)
        w_t = torch.tensor(ws,   dtype=torch.float32)
        h_t = torch.tensor(hs,   dtype=torch.float32)

        gx = cx / stride
        gy = cy / stride
        ix = gx.long().clamp(0, W - 1)
        iy = gy.long().clamp(0, H - 1)

        tx = gx - ix.float()
        ty = gy - iy.float()
        tw = (w_t / cfg.img_size) / cfg.wh_scale
        th = (h_t / cfg.img_size) / cfg.wh_scale

        # Scatter vers les tenseurs cibles
        # En cas de collision (deux objets → même cellule), la dernière
        # annotation l'emporte — comportement identique à la version naïve.
        cls_t[b, cls_t_img, iy, ix] = 1.0
        obj_t[b, 0,         iy, ix] = 1.0
        box_t[b, 0,         iy, ix] = tx
        box_t[b, 1,         iy, ix] = ty
        box_t[b, 2,         iy, ix] = tw
        box_t[b, 3,         iy, ix] = th

    return cls_t, obj_t, box_t


def make_collate(cfg: Config, label_map: dict[int, int]):
    """Factory : renvoie une collate_fn capturant cfg et label_map."""
    H = W = cfg.feature_size

    def collate_fn(batch):
        imgs, targets = zip(*batch)
        cls_t, obj_t, box_t = build_targets(
            targets, len(batch), H, W, cfg, label_map
        )
        return torch.stack(imgs), cls_t, obj_t, box_t

    return collate_fn


# ============================================================
# LOSS
# ============================================================
def focal_loss(
    pred:   torch.Tensor,
    target: torch.Tensor,
    alpha:  float = 0.25,
    gamma:  float = 2.0,
) -> torch.Tensor:
    """Binary focal loss numériquement stable (via logits)."""
    pred_sig = torch.sigmoid(pred)
    pt  = pred_sig * target + (1 - pred_sig) * (1 - target)
    bce = F.binary_cross_entropy_with_logits(pred, target, reduction="none")
    return (alpha * (1 - pt) ** gamma * bce).mean()


def compute_loss(
    cls_p: torch.Tensor, obj_p: torch.Tensor, box_p: torch.Tensor,
    cls_t: torch.Tensor, obj_t: torch.Tensor, box_t: torch.Tensor,
    cfg:    Config,
    device: torch.device,
) -> tuple[torch.Tensor, dict[str, float]]:
    cls_loss = focal_loss(cls_p, cls_t, cfg.focal_alpha, cfg.focal_gamma)
    obj_loss = F.binary_cross_entropy_with_logits(obj_p, obj_t)

    mask = (obj_t > 0).squeeze(1)   # [B, H, W]
    if mask.any():
        p = box_p.permute(0, 2, 3, 1)[mask]   # [N, 4] — sorties brutes
        g = box_t.permute(0, 2, 3, 1)[mask]   # [N, 4] — cibles ∈ [0,1]

        # Sigmoid sur toutes les composantes : cohérent avec encode_box
        p_sig = torch.sigmoid(p)      # ∈ (0,1)
        box_loss = F.smooth_l1_loss(p_sig, g)
    else:
        box_loss = torch.tensor(0.0, device=device)

    total = cfg.w_cls * cls_loss + cfg.w_obj * obj_loss + cfg.w_box * box_loss
    details = {
        "loss/cls":   cls_loss.item(),
        "loss/obj":   obj_loss.item(),
        "loss/box":   box_loss.item(),
        "loss/total": total.item(),
    }
    return total, details


# ============================================================
# DECODE (inférence) — pure sigmoid, symétrique avec l'encoding
# ============================================================
def decode(
    cls: torch.Tensor,
    obj: torch.Tensor,
    box: torch.Tensor,
    cfg: Config,
) -> Optional[tuple[torch.Tensor, torch.Tensor, torch.Tensor]]:
    """
    Décode les prédictions brutes → boîtes (x1,y1,x2,y2) absolues.
    Retourne (boxes [N,4], scores [N], labels [N]) ou None.
    """
    B, _, H, W = cls.shape
    stride = cfg.img_size / H
    device = cls.device

    scores = torch.sigmoid(cls) * torch.sigmoid(obj)   # [B, C, H, W]
    conf, label = scores.max(dim=1)                     # [B, H, W]
    keep = conf > cfg.conf_threshold

    if not keep.any():
        return None

    gy, gx = torch.meshgrid(
        torch.arange(H, device=device, dtype=torch.float32),
        torch.arange(W, device=device, dtype=torch.float32),
        indexing="ij",
    )
    gx = gx.unsqueeze(0).expand(B, -1, -1)
    gy = gy.unsqueeze(0).expand(B, -1, -1)

    raw  = box.permute(0, 2, 3, 1)[keep]   # [N, 4]
    b_gx = gx[keep]
    b_gy = gy[keep]

    pred_cx, pred_cy, pred_w, pred_h = decode_box(
        raw, b_gx, b_gy, stride, cfg.img_size, cfg.wh_scale
    )

    x1 = pred_cx - pred_w / 2
    y1 = pred_cy - pred_h / 2
    x2 = pred_cx + pred_w / 2
    y2 = pred_cy + pred_h / 2

    return (
        torch.stack([x1, y1, x2, y2], dim=1),
        conf[keep],
        label[keep],
    )


def decode_with_nms(
    cls: torch.Tensor, obj: torch.Tensor, box: torch.Tensor, cfg: Config,
) -> list[Optional[tuple[torch.Tensor, torch.Tensor, torch.Tensor]]]:
    """NMS par image. Retourne liste de (boxes, scores, labels) ou None."""
    result = decode(cls, obj, box, cfg)
    if result is None:
        return [None]

    boxes, scores, labels = result
    keep_idx = nms(boxes, scores, cfg.nms_iou_threshold)
    return [(boxes[keep_idx], scores[keep_idx], labels[keep_idx])]


# ============================================================
# MODULE mAP
# ============================================================

def _iou_single(box_a: torch.Tensor, box_b: torch.Tensor) -> torch.Tensor:
    """IoU entre deux tenseurs de boîtes [N,4] et [M,4]. Retourne [N,M]."""
    return box_iou(box_a, box_b)


def compute_precision_recall(
    pred_boxes:   torch.Tensor,   # [N, 4] x1y1x2y2
    pred_scores:  torch.Tensor,   # [N]
    pred_labels:  torch.Tensor,   # [N]
    gt_boxes:     torch.Tensor,   # [M, 4]
    gt_labels:    torch.Tensor,   # [M]
    num_classes:  int,
    iou_threshold: float = 0.5,
) -> dict[int, tuple[np.ndarray, np.ndarray]]:
    """
    Calcule les courbes précision/rappel par classe pour une image.

    Retourne un dict {class_id: (precisions, recalls)} où chaque élément
    est un ndarray trié par score décroissant.
    """
    results: dict[int, tuple[np.ndarray, np.ndarray]] = {}

    for cls_id in range(num_classes):
        pred_mask = pred_labels == cls_id
        gt_mask   = gt_labels   == cls_id

        p_boxes  = pred_boxes[pred_mask]
        p_scores = pred_scores[pred_mask]
        g_boxes  = gt_boxes[gt_mask]

        n_gt = g_boxes.shape[0]
        n_p  = p_boxes.shape[0]

        if n_gt == 0 and n_p == 0:
            continue

        if n_p == 0:
            results[cls_id] = (np.array([0.0]), np.array([0.0]))
            continue

        # Tri par score décroissant
        order    = p_scores.argsort(descending=True)
        p_boxes  = p_boxes[order]
        p_scores = p_scores[order]

        tp = np.zeros(n_p, dtype=np.float32)
        fp = np.zeros(n_p, dtype=np.float32)
        matched = np.zeros(n_gt, dtype=bool)

        if n_gt > 0:
            ious = box_iou(p_boxes, g_boxes).cpu().numpy()   # [n_p, n_gt]
            for i in range(n_p):
                best_iou  = -1.0
                best_gt   = -1
                for j in range(n_gt):
                    if not matched[j] and ious[i, j] > best_iou:
                        best_iou = ious[i, j]
                        best_gt  = j
                if best_iou >= iou_threshold:
                    tp[i] = 1.0
                    matched[best_gt] = True
                else:
                    fp[i] = 1.0
        else:
            fp[:] = 1.0

        cum_tp = np.cumsum(tp)
        cum_fp = np.cumsum(fp)
        recalls    = cum_tp / (n_gt + 1e-9)
        precisions = cum_tp / (cum_tp + cum_fp + 1e-9)

        results[cls_id] = (precisions, recalls)

    return results


def _ap_from_pr(precisions: np.ndarray, recalls: np.ndarray) -> float:
    """
    Calcule l'AP par interpolation 11 points (style VOC 2010).
    Plus robuste que l'AUC trapézoïdal pour de petits datasets.
    """
    ap = 0.0
    for thr in np.linspace(0, 1, 11):
        mask = recalls >= thr
        ap  += precisions[mask].max() if mask.any() else 0.0
    return ap / 11.0


def per_class_ap(
    all_pred_boxes:  list[torch.Tensor],   # par image
    all_pred_scores: list[torch.Tensor],
    all_pred_labels: list[torch.Tensor],
    all_gt_boxes:    list[torch.Tensor],
    all_gt_labels:   list[torch.Tensor],
    num_classes: int,
    iou_threshold: float = 0.5,
) -> dict[int, float]:
    """
    Calcule l'AP@iou_threshold pour chaque classe sur l'ensemble du dataset.

    Stratégie : accumulation de tous les TP/FP sur toutes les images,
    puis courbe P/R globale (Pascal VOC style).
    """
    # Accumulateurs par classe : liste de (score, is_tp)
    class_preds: dict[int, list[tuple[float, int]]] = defaultdict(list)
    class_n_gt:  dict[int, int]                     = defaultdict(int)

    for p_boxes, p_scores, p_labels, g_boxes, g_labels in zip(
        all_pred_boxes, all_pred_scores, all_pred_labels,
        all_gt_boxes,   all_gt_labels,
    ):
        # Compter les GT par classe
        for cls_id in g_labels.tolist():
            class_n_gt[int(cls_id)] += 1

        for cls_id in range(num_classes):
            pred_mask = p_labels == cls_id
            gt_mask   = g_labels == cls_id

            p_b = p_boxes[pred_mask]
            p_s = p_scores[pred_mask]
            g_b = g_boxes[gt_mask]

            if p_b.shape[0] == 0:
                continue

            order = p_s.argsort(descending=True)
            p_b   = p_b[order]
            p_s   = p_s[order]

            matched = np.zeros(g_b.shape[0], dtype=bool)

            if g_b.shape[0] > 0:
                ious = box_iou(p_b, g_b).cpu().numpy()
                for i in range(p_b.shape[0]):
                    best_iou, best_gt = -1.0, -1
                    for j in range(g_b.shape[0]):
                        if not matched[j] and ious[i, j] > best_iou:
                            best_iou, best_gt = ious[i, j], j
                    is_tp = int(best_iou >= iou_threshold)
                    if is_tp:
                        matched[best_gt] = True
                    class_preds[cls_id].append((p_s[i].item(), is_tp))
            else:
                for i in range(p_b.shape[0]):
                    class_preds[cls_id].append((p_s[i].item(), 0))

    ap_per_class: dict[int, float] = {}
    for cls_id in range(num_classes):
        n_gt = class_n_gt.get(cls_id, 0)
        if n_gt == 0:
            ap_per_class[cls_id] = float("nan")
            continue

        preds = sorted(class_preds.get(cls_id, []), key=lambda x: -x[0])
        if not preds:
            ap_per_class[cls_id] = 0.0
            continue

        tp_arr = np.array([p[1] for p in preds], dtype=np.float32)
        cum_tp = np.cumsum(tp_arr)
        cum_fp = np.cumsum(1 - tp_arr)
        recalls    = cum_tp / (n_gt + 1e-9)
        precisions = cum_tp / (cum_tp + cum_fp + 1e-9)
        ap_per_class[cls_id] = _ap_from_pr(precisions, recalls)

    return ap_per_class


def compute_map_50(
    all_pred_boxes:  list[torch.Tensor],
    all_pred_scores: list[torch.Tensor],
    all_pred_labels: list[torch.Tensor],
    all_gt_boxes:    list[torch.Tensor],
    all_gt_labels:   list[torch.Tensor],
    num_classes: int,
    iou_threshold: float = 0.5,
) -> tuple[float, dict[int, float]]:
    """
    Point d'entrée principal pour l'évaluation.

    Retourne (mAP@0.5, {class_id: AP}) où mAP est la moyenne sur
    les classes qui ont au moins un GT (NaN exclus).
    """
    ap_dict = per_class_ap(
        all_pred_boxes, all_pred_scores, all_pred_labels,
        all_gt_boxes,   all_gt_labels,
        num_classes,    iou_threshold,
    )
    valid_aps = [v for v in ap_dict.values() if not math.isnan(v)]
    map50 = float(np.mean(valid_aps)) if valid_aps else 0.0
    return map50, ap_dict


def compute_map_coco(
    all_pred_boxes:  list[torch.Tensor],
    all_pred_scores: list[torch.Tensor],
    all_pred_labels: list[torch.Tensor],
    all_gt_boxes:    list[torch.Tensor],
    all_gt_labels:   list[torch.Tensor],
) -> Optional[dict[str, float]]:
    """
    mAP COCO strict via pycocotools (mAP@[.5:.95], AP50, AP75, APs/APm/APl).

    Retourne un dict de métriques, ou None si pycocotools n'est pas installé.
    Utiliser en évaluation finale ; trop lent pour chaque epoch d'entraînement.

    Installation : pip install pycocotools
    """
    try:
        from pycocotools.coco import COCO
        from pycocotools.cocoeval import COCOeval
    except ImportError:
        log.warning(
            "pycocotools non installé — mAP COCO strict ignoré. "
            "pip install pycocotools pour l'activer."
        )
        return None

    # Construction des structures COCO in-memory
    gt_coco: dict = {"images": [], "annotations": [], "categories": []}
    dt_list: list = []
    ann_id = 1

    # Catégories fictives (une par index de classe)
    seen_cats: set[int] = set()
    for g_labels in all_gt_labels:
        for c in g_labels.tolist():
            seen_cats.add(int(c))
    gt_coco["categories"] = [{"id": c, "name": str(c)} for c in sorted(seen_cats)]

    for img_id, (p_boxes, p_scores, p_labels, g_boxes, g_labels) in enumerate(zip(
        all_pred_boxes, all_pred_scores, all_pred_labels,
        all_gt_boxes,   all_gt_labels,
    )):
        gt_coco["images"].append({"id": img_id})

        for box, label in zip(g_boxes.tolist(), g_labels.tolist()):
            x1, y1, x2, y2 = box
            gt_coco["annotations"].append({
                "id": ann_id, "image_id": img_id,
                "category_id": int(label),
                "bbox": [x1, y1, x2 - x1, y2 - y1],
                "area": max(0.0, (x2 - x1) * (y2 - y1)),
                "iscrowd": 0,
            })
            ann_id += 1

        for box, score, label in zip(p_boxes.tolist(), p_scores.tolist(), p_labels.tolist()):
            x1, y1, x2, y2 = box
            dt_list.append({
                "image_id": img_id,
                "category_id": int(label),
                "bbox": [x1, y1, x2 - x1, y2 - y1],
                "score": float(score),
            })

    if not dt_list:
        return {"coco/mAP": 0.0, "coco/AP50": 0.0, "coco/AP75": 0.0}

    import tempfile, json
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
        json.dump(gt_coco, f)
        gt_path = f.name

    coco_gt = COCO(gt_path)
    coco_dt = coco_gt.loadRes(dt_list)
    ev = COCOeval(coco_gt, coco_dt, "bbox")
    ev.evaluate()
    ev.accumulate()
    ev.summarize()

    return {
        "coco/mAP":    float(ev.stats[0]),   # mAP@[.5:.95]
        "coco/AP50":   float(ev.stats[1]),   # AP@0.5
        "coco/AP75":   float(ev.stats[2]),   # AP@0.75
        "coco/APs":    float(ev.stats[3]),   # AP small
        "coco/APm":    float(ev.stats[4]),   # AP medium
        "coco/APl":    float(ev.stats[5]),   # AP large
    }


def compute_detection_metrics(
    all_pred_boxes:  list[torch.Tensor],
    all_pred_scores: list[torch.Tensor],
    all_pred_labels: list[torch.Tensor],
    all_gt_boxes:    list[torch.Tensor],
    all_gt_labels:   list[torch.Tensor],
    iou_threshold:   float = 0.5,
) -> dict[str, float]:
    """
    Calcule Precision, Recall et F1 globaux (toutes classes confondues)
    à partir des listes d'accumulateurs déjà construites par evaluate_map.

    Matching strict : une prédiction est TP seulement si
      - IoU ≥ iou_threshold avec un GT non encore matché
      - la classe prédite correspond à la classe GT

    Les prédictions sont triées par score décroissant avant matching
    (conforme au protocole Pascal VOC).
    """
    total_tp = 0
    total_fp = 0
    total_fn = 0

    for p_boxes, p_scores, p_labels, g_boxes, g_labels in zip(
        all_pred_boxes, all_pred_scores, all_pred_labels,
        all_gt_boxes,   all_gt_labels,
    ):
        n_gt = g_boxes.shape[0]
        n_p  = p_boxes.shape[0]

        if n_p == 0:
            total_fn += n_gt
            continue

        if n_gt == 0:
            total_fp += n_p
            continue

        # Tri par score décroissant pour un matching greedy cohérent
        order   = p_scores.argsort(descending=True)
        p_boxes  = p_boxes[order]
        p_labels = p_labels[order]

        ious    = box_iou(p_boxes, g_boxes).cpu()   # [n_p, n_gt]
        matched = torch.zeros(n_gt, dtype=torch.bool)

        for i in range(n_p):
            # Parmi les GT non matchés de la même classe, trouver le meilleur IoU
            same_class = (p_labels[i] == g_labels)        # [n_gt]
            candidates = same_class & ~matched             # [n_gt]

            if not candidates.any():
                total_fp += 1
                continue

            iou_row            = ious[i].clone()
            iou_row[~candidates] = -1.0
            best_iou, best_j   = iou_row.max(dim=0)

            if best_iou >= iou_threshold:
                total_tp        += 1
                matched[best_j]  = True
            else:
                total_fp += 1

        total_fn += int((~matched).sum().item())

    precision = total_tp / (total_tp + total_fp + 1e-9)
    recall    = total_tp / (total_tp + total_fn + 1e-9)
    f1        = 2 * precision * recall / (precision + recall + 1e-9)

    return {
        "metrics/precision": float(precision),
        "metrics/recall":    float(recall),
        "metrics/f1":        float(f1),
    }


@torch.no_grad()
def evaluate_map(
    model:      nn.Module,
    loader:     DataLoader,
    cfg:        Config,
    device:     torch.device,
    max_images: Optional[int] = None,
) -> tuple[float, dict[int, float]]:
    """
    Lance l'inférence sur `loader` et calcule mAP@cfg.map_iou_threshold.

    `max_images` limite le nombre d'images évaluées (utile pendant l'entraînement).
    Retourne (mAP50, per_class_AP).
    """
    model.eval()
    all_pred_boxes:  list[torch.Tensor] = []
    all_pred_scores: list[torch.Tensor] = []
    all_pred_labels: list[torch.Tensor] = []
    all_gt_boxes:    list[torch.Tensor] = []
    all_gt_labels:   list[torch.Tensor] = []

    n_images = 0
    stride   = cfg.img_size / cfg.feature_size

    for imgs, cls_t, obj_t, box_t in tqdm(loader, desc="mAP eval", leave=False):
        imgs = imgs.to(device, non_blocking=True)
        cls_p, obj_p, box_p = model(imgs)

        B, _, H, W = cls_p.shape

        # Reconstruire les GT à partir des box_t pour éviter de stocker les anns
        gy_grid, gx_grid = torch.meshgrid(
            torch.arange(H, dtype=torch.float32),
            torch.arange(W, dtype=torch.float32),
            indexing="ij",
        )

        for b in range(B):
            # ---- Prédictions — tout reste sur GPU jusqu'après NMS ----
            result = decode(cls_p[b:b+1], obj_p[b:b+1], box_p[b:b+1], cfg)
            if result is not None:
                boxes, scores, labels = result
                keep_idx = nms(boxes, scores, cfg.nms_iou_threshold)
                # Transfer CPU unique, après NMS (N détections << H×W)
                all_pred_boxes.append(boxes[keep_idx].cpu())
                all_pred_scores.append(scores[keep_idx].cpu())
                all_pred_labels.append(labels[keep_idx].cpu())
            else:
                all_pred_boxes.append(torch.zeros((0, 4)))
                all_pred_scores.append(torch.zeros(0))
                all_pred_labels.append(torch.zeros(0, dtype=torch.long))

            # ---- Ground truth reconstruit depuis box_t / cls_t ----
            pos_mask = (obj_t[b, 0] > 0)   # [H, W]
            pos_iy, pos_ix = pos_mask.nonzero(as_tuple=True)

            if pos_iy.numel() > 0:
                raw_box = box_t[b, :, pos_iy, pos_ix].T   # [N, 4]
                # Inverser encode_box : tx,ty ∈ [0,1] ; tw,th ∈ [0,1]
                cx = (raw_box[:, 0] + pos_ix.float()) * stride
                cy = (raw_box[:, 1] + pos_iy.float()) * stride
                w  = raw_box[:, 2] * cfg.wh_scale * cfg.img_size
                h  = raw_box[:, 3] * cfg.wh_scale * cfg.img_size
                gt_x1 = cx - w / 2
                gt_y1 = cy - h / 2
                gt_x2 = cx + w / 2
                gt_y2 = cy + h / 2
                gt_boxes_b = torch.stack([gt_x1, gt_y1, gt_x2, gt_y2], dim=1)

                # Label : argmax de cls_t sur les cellules positives
                gt_labels_b = cls_t[b, :, pos_iy, pos_ix].argmax(dim=0)

                all_gt_boxes.append(gt_boxes_b)
                all_gt_labels.append(gt_labels_b)
            else:
                all_gt_boxes.append(torch.zeros((0, 4)))
                all_gt_labels.append(torch.zeros(0, dtype=torch.long))

            n_images += 1
            if max_images is not None and n_images >= max_images:
                break

        if max_images is not None and n_images >= max_images:
            break

    map50, ap_dict = compute_map_50(
        all_pred_boxes, all_pred_scores, all_pred_labels,
        all_gt_boxes,   all_gt_labels,
        cfg.num_classes, cfg.map_iou_threshold,
    )
    # P/R/F1 dérivés des mêmes accumulateurs — pas de second parcours
    det_metrics = compute_detection_metrics(
        all_pred_boxes, all_pred_scores, all_pred_labels,
        all_gt_boxes,   all_gt_labels,
        iou_threshold=cfg.map_iou_threshold,
    )
    return map50, ap_dict, det_metrics


# ============================================================
# CHECKPOINT
# ============================================================
class CheckpointManager:
    def __init__(self, ckpt_dir: str) -> None:
        self.ckpt_dir = Path(ckpt_dir)
        self.ckpt_dir.mkdir(parents=True, exist_ok=True)

    def save(
        self,
        epoch:     int,
        model:     nn.Module,
        optimizer: torch.optim.Optimizer,
        scheduler,
        metrics:   dict,
        cfg:       Config,
    ) -> Path:
        path = self.ckpt_dir / f"epoch_{epoch:04d}.pt"
        torch.save({
            "epoch":     epoch,
            "model":     model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "metrics":   metrics,
            "cfg":       cfg.__dict__,
        }, path)
        log.info("Checkpoint sauvegardé : %s", path)
        return path

    def load(
        self,
        path:      str,
        model:     nn.Module,
        optimizer: torch.optim.Optimizer,
        scheduler,
    ) -> int:
        ckpt = torch.load(path, map_location="cpu")
        model.load_state_dict(ckpt["model"])
        optimizer.load_state_dict(ckpt["optimizer"])
        scheduler.load_state_dict(ckpt["scheduler"])
        log.info("Reprise depuis %s (epoch %d)", path, ckpt["epoch"])
        return ckpt["epoch"]


# ============================================================
# BOUCLE D'ENTRAÎNEMENT
# ============================================================
def _gpu_mem_str(device: torch.device) -> str:
    """Retourne la mémoire GPU réservée formatée (ex: '3.2G'), ou '' sur CPU."""
    if device.type != "cuda":
        return ""
    try:
        mem = torch.cuda.memory_reserved(device) / 1e9
        return f"{mem:.2f}G"
    except Exception:
        return ""


def _print_epoch_header() -> None:
    """Imprime l'en-tête de tableau style Ultralytics."""
    print(
        f"\n{'':>10s}{'gpu_mem':>10s}"
        f"{'box_loss':>10s}{'cls_loss':>10s}{'obj_loss':>10s}"
        f"{'val_box':>10s}{'val_cls':>10s}{'val_obj':>10s}"
        f"{'P':>8s}{'R':>8s}{'mAP50':>9s}{'lr':>12s}",
        flush=True,
    )


def run_epoch(
    model:        nn.Module,
    loader:       DataLoader,
    optimizer:    torch.optim.Optimizer,
    scaler:       torch.amp.GradScaler,
    cfg:          Config,
    device:       torch.device,
    writer=None,
    global_step:  int = 0,
    train:        bool = True,
    epoch:        int = 0,
    total_epochs: int = 0,
) -> tuple[dict[str, float], int]:
    model.train(train)
    totals:    dict[str, float] = {}
    n_batches: int = 0
    ctx = torch.amp.autocast("cuda", enabled=(device.type == "cuda"))

    phase = "train" if train else "val"
    desc  = (f"Epoch {epoch}/{total_epochs} [{phase}]"
             if total_epochs > 0 else phase)

    with tqdm(loader, desc=desc, leave=False) as pbar:
        for step, (imgs, cls_t, obj_t, box_t) in enumerate(pbar):
            imgs  = imgs.to(device,  non_blocking=True)
            cls_t = cls_t.to(device, non_blocking=True)
            obj_t = obj_t.to(device, non_blocking=True)
            box_t = box_t.to(device, non_blocking=True)

            with ctx:
                cls_p, obj_p, box_p = model(imgs)
                loss, details = compute_loss(
                    cls_p, obj_p, box_p, cls_t, obj_t, box_t, cfg, device
                )

            if train:
                optimizer.zero_grad(set_to_none=True)
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
                scaler.step(optimizer)
                scaler.update()

                if writer:
                    for k, v in details.items():
                        writer.add_scalar(k, v, global_step)
                global_step += 1

            for k, v in details.items():
                totals[k] = totals.get(k, 0.0) + v
            n_batches += 1
            avg_box = totals.get("loss/box", 0.0) / n_batches
            avg_cls = totals.get("loss/cls", 0.0) / n_batches
            avg_obj = totals.get("loss/obj", 0.0) / n_batches
            mem = _gpu_mem_str(device)
            postfix: dict = {
                "box": f"{avg_box:.4f}",
                "cls": f"{avg_cls:.4f}",
                "obj": f"{avg_obj:.4f}",
            }
            if mem:
                postfix = {"mem": mem, **postfix}
            pbar.set_postfix(postfix)

            if cfg.max_steps is not None and step >= cfg.max_steps - 1:
                log.debug("max_steps=%d atteint.", cfg.max_steps)
                break

    averages = {k: v / n_batches for k, v in totals.items()}
    return averages, global_step


def train(cfg: Config = CFG) -> None:
    set_seed(cfg.seed)
    device = cfg.device
    log.info("Device : %s", device)

    if not (Path(cfg.img_dir).exists() and Path(cfg.ann_path).exists()):
        log.error("Dataset introuvable : %s / %s", cfg.img_dir, cfg.ann_path)
        return

    transform = T.Compose([
        T.Resize((cfg.img_size, cfg.img_size)),
        T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        T.ToTensor(),
    ])

    full_dataset = CocoDetection(cfg.img_dir, cfg.ann_path, transform=transform)
    n_val   = max(1, int(len(full_dataset) * cfg.val_split))
    n_train = len(full_dataset) - n_val
    train_ds, val_ds = random_split(
        full_dataset, [n_train, n_val],
        generator=torch.Generator().manual_seed(cfg.seed),
    )
    log.info("Dataset : %d train, %d val", n_train, n_val)

    # Mapping dynamique — ignore coco_valid_ids si vide, sinon le valide
    if cfg.coco_valid_ids:
        label_map  = cfg.label_map
        num_classes = cfg.num_classes
    else:
        label_map, num_classes = build_label_map_from_annotations(cfg.ann_path)
        if num_classes != cfg.num_classes:
            log.warning(
                "num_classes config (%d) ≠ annotations (%d) — on utilise %d",
                cfg.num_classes, num_classes, num_classes,
            )

    collate      = make_collate(cfg, label_map)
    n_workers    = min(4, os.cpu_count() or 1)
    train_loader = DataLoader(
        train_ds, batch_size=cfg.batch_size, shuffle=True,
        collate_fn=collate, num_workers=n_workers,
        pin_memory=(device.type == "cuda"), persistent_workers=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=cfg.batch_size, shuffle=False,
        collate_fn=collate, num_workers=max(1, n_workers // 2),
        pin_memory=(device.type == "cuda"), persistent_workers=True,
    )

    model = NanoDetLite(cfg.num_classes).to(device)
    log.info("Paramètres : %.2f M",
             sum(p.numel() for p in model.parameters()) / 1e6)

    optimizer   = torch.optim.AdamW(
        model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay
    )
    total_steps = cfg.epochs * len(train_loader)
    scheduler   = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=total_steps, eta_min=cfg.lr * 1e-2
    )
    scaler   = torch.amp.GradScaler("cuda", enabled=(device.type == "cuda"))
    ckpt_mgr = CheckpointManager(cfg.ckpt_dir)
    writer   = SummaryWriter(LOG_DIR / "tb") if _TB_AVAILABLE else None

    start_epoch = 0
    global_step = 0
    if cfg.resume:
        start_epoch = ckpt_mgr.load(cfg.resume, model, optimizer, scheduler)

    best_map50 = 0.0
    _print_epoch_header()

    for epoch in range(start_epoch, cfg.epochs):

        train_metrics, global_step = run_epoch(
            model, train_loader, optimizer, scaler, cfg, device,
            writer=writer, global_step=global_step, train=True,
            epoch=epoch + 1, total_epochs=cfg.epochs,
        )
        scheduler.step()

        with torch.no_grad():
            val_metrics, _ = run_epoch(
                model, val_loader, optimizer, scaler, cfg, device,
                writer=writer, global_step=global_step, train=False,
                epoch=epoch + 1, total_epochs=cfg.epochs,
            )

        # mAP + P/R/F1 sur un sous-ensemble pour limiter le temps de calcul
        map50, ap_dict, det_metrics = evaluate_map(
            model, val_loader, cfg, device, max_images=500
        )

        # ── Ligne de tableau style Ultralytics ──────────────────────────────
        lr_now  = optimizer.param_groups[0]["lr"]
        mem_str = _gpu_mem_str(device)
        epoch_str = f"{epoch + 1}/{cfg.epochs}"
        print(
            f"{epoch_str:>10s}{mem_str:>10s}"
            f"{train_metrics.get('loss/box', 0):>10.4f}"
            f"{train_metrics.get('loss/cls', 0):>10.4f}"
            f"{train_metrics.get('loss/obj', 0):>10.4f}"
            f"{val_metrics.get('loss/box', 0):>10.4f}"
            f"{val_metrics.get('loss/cls', 0):>10.4f}"
            f"{val_metrics.get('loss/obj', 0):>10.4f}"
            f"{det_metrics['metrics/precision']:>8.3f}"
            f"{det_metrics['metrics/recall']:>8.3f}"
            f"{map50:>9.4f}"
            f"{lr_now:>12.2e}",
            flush=True,
        )

        # ── Tableau par classe style Ultralytics ────────────────────────────
        valid_aps = [(c, v) for c, v in ap_dict.items() if not math.isnan(v)]
        if valid_aps:
            print(
                f"\n{'':>18s}{'Class':>10s}{'AP50':>10s}",
                flush=True,
            )
            for cls_id, ap in sorted(valid_aps, key=lambda x: -x[1])[:10]:
                print(f"{'':>18s}{f'cls{cls_id}':>10s}{ap:>10.3f}", flush=True)
            mean_ap = sum(v for _, v in valid_aps) / len(valid_aps)
            print(f"{'':>18s}{'all':>10s}{mean_ap:>10.3f}\n", flush=True)

        if writer:
            for k, v in val_metrics.items():
                writer.add_scalar("val/" + k.split("/")[1], v, epoch)
            writer.add_scalar("metrics/mAP50", map50, epoch)
            for k, v in det_metrics.items():
                writer.add_scalar(k, v, epoch)
            writer.add_scalar("lr", lr_now, epoch)

        if (epoch + 1) % cfg.save_every == 0:
            ckpt_mgr.save(
                epoch + 1, model, optimizer, scheduler,
                {**val_metrics, "mAP50": map50, **det_metrics}, cfg,
            )

        if map50 > best_map50:
            best_map50 = map50
            best_path  = Path(cfg.ckpt_dir) / "best.pt"
            torch.save(model.state_dict(), best_path)
            print(f"  ✦ best model saved  mAP50={best_map50:.4f}", flush=True)

    if writer:
        writer.close()
    print(f"\n✔ ENTRAÎNEMENT TERMINÉ  best mAP50={best_map50:.4f}", flush=True)


# ============================================================
# EXPORT ONNX
# ============================================================
def export_onnx(
    model:        Optional[nn.Module] = None,
    cfg:          Config              = CFG,
    weights_path: Optional[str]       = None,
) -> None:
    """Exporte et vérifie la cohérence PyTorch / OnnxRuntime."""
    if model is None:
        model = NanoDetLite(cfg.num_classes)
        if weights_path:
            ckpt  = torch.load(weights_path, map_location="cpu")
            state = ckpt.get("model", ckpt)
            model.load_state_dict(state)
            log.info("Poids chargés depuis %s", weights_path)

    model.eval().cpu()
    dummy = torch.randn(1, 3, cfg.img_size, cfg.img_size)

    torch.onnx.export(
        model, dummy, cfg.onnx_path,
        input_names=["input"],
        output_names=["cls", "obj", "box"],
        opset_version=cfg.opset,
        dynamic_axes={"input": {0: "batch"}},
        do_constant_folding=False,
    )
    log.info("ONNX exporté : %s", cfg.onnx_path)

    # Garantit un fichier ONNX unique (sans données externes séparées)
    try:
        import onnx as _onnx_mod
        _proto = _onnx_mod.load(cfg.onnx_path)
        _onnx_mod.save_model(
            _proto, cfg.onnx_path,
            save_as_external_data=False,
        )
        log.info("ONNX sauvegardé en fichier unique : %s", cfg.onnx_path)
    except ImportError:
        log.warning("onnx non installé — impossble de garantir le fichier unique.")

    try:
        import onnx
        import onnxruntime as ort

        onnx.checker.check_model(onnx.load(cfg.onnx_path))
        sess     = ort.InferenceSession(cfg.onnx_path, providers=["CPUExecutionProvider"])
        ort_outs = sess.run(None, {"input": dummy.numpy()})

        with torch.no_grad():
            pt_outs = [t.numpy() for t in model(dummy)]

        for i, (pt, ort_out) in enumerate(zip(pt_outs, ort_outs)):
            max_diff = np.abs(pt - ort_out).max()
            log.info("Output[%d] max_diff PyTorch/ONNX = %.2e", i, max_diff)
            assert max_diff < 1e-4, f"Écart trop grand sur output[{i}] : {max_diff}"

        log.info("✔ ONNX vérifié (cohérence PyTorch / OnnxRuntime OK)")

    except ImportError:
        log.warning("onnxruntime/onnx non installé — vérification ignorée.")
    except AssertionError as e:
        log.error("Vérification ONNX échouée : %s", e)
        raise


# ============================================================
# INFÉRENCE ONNX SUR IMAGE
# ============================================================
def infer_onnx(
    image_path:  str,
    onnx_path:   Optional[str]       = None,
    cfg:         Config               = CFG,
    class_names: Optional[list[str]] = None,
    output_path: Optional[str]       = None,
) -> list[dict]:
    """
    Lance l'inférence sur une image à partir du fichier ONNX produit.

    Args:
        image_path  : chemin vers l'image d'entrée (JPEG/PNG…)
        onnx_path   : chemin vers le .onnx (défaut : cfg.onnx_path)
        cfg         : configuration (conf_threshold, nms_iou_threshold, img_size…)
        class_names : liste des noms de classes (ex. COCO 80 classes)
        output_path : si fourni, sauvegarde l'image annotée à ce chemin

    Returns:
        Liste de dict {"box": [x1,y1,x2,y2], "score": float,
                       "label": int, "class_name": str}
    """
    try:
        import onnxruntime as ort
    except ImportError:
        raise ImportError("onnxruntime requis : pip install onnxruntime")

    try:
        from PIL import Image as PILImage
    except ImportError:
        raise ImportError("Pillow requis : pip install Pillow")

    if onnx_path is None:
        onnx_path = cfg.onnx_path

    # ── Chargement & préprocessing ──────────────────────────────────────────
    img      = PILImage.open(image_path).convert("RGB")
    orig_w, orig_h = img.size
    img_resized    = img.resize((cfg.img_size, cfg.img_size))
    img_np         = np.array(img_resized, dtype=np.float32) / 255.0
    img_tensor     = (
        torch.from_numpy(img_np).permute(2, 0, 1).unsqueeze(0)
    )  # [1, 3, H, W]

    # ── Inférence ONNX ──────────────────────────────────────────────────────
    log.info("Inférence ONNX sur %s (modèle : %s)", image_path, onnx_path)
    sess = ort.InferenceSession(
        onnx_path, providers=["CPUExecutionProvider"]
    )
    cls_np, obj_np, box_np = sess.run(None, {"input": img_tensor.numpy()})

    cls_t = torch.from_numpy(cls_np)
    obj_t = torch.from_numpy(obj_np)
    box_t = torch.from_numpy(box_np)

    # ── Décodage + NMS ──────────────────────────────────────────────────────
    result = decode(cls_t, obj_t, box_t, cfg)
    if result is None:
        log.info("Aucune détection sur %s", image_path)
        return []

    boxes, scores, labels = result
    keep_idx = nms(boxes, scores, cfg.nms_iou_threshold)
    boxes    = boxes[keep_idx].numpy()
    scores   = scores[keep_idx].numpy()
    labels   = labels[keep_idx].numpy()

    # ── Mise à l'échelle → coordonnées image originale ──────────────────────
    scale_x = orig_w / cfg.img_size
    scale_y = orig_h / cfg.img_size

    detections: list[dict] = []
    for box, score, label in zip(boxes, scores, labels):
        x1 = float(box[0]) * scale_x
        y1 = float(box[1]) * scale_y
        x2 = float(box[2]) * scale_x
        y2 = float(box[3]) * scale_y
        cls_name = (
            class_names[int(label)]
            if class_names and int(label) < len(class_names)
            else f"cls{int(label)}"
        )
        det = {
            "box":        [x1, y1, x2, y2],
            "score":      float(score),
            "label":      int(label),
            "class_name": cls_name,
        }
        detections.append(det)
        log.info("  [%s] score=%.3f  box=[%.1f, %.1f, %.1f, %.1f]",
                 cls_name, score, x1, y1, x2, y2)

    # ── Annotation et sauvegarde ─────────────────────────────────────────────
    if output_path and detections:
        try:
            import cv2
            img_cv = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
            for det in detections:
                bx1, by1, bx2, by2 = [int(v) for v in det["box"]]
                cv2.rectangle(img_cv, (bx1, by1), (bx2, by2), (0, 255, 0), 2)
                label_str = f"{det['class_name']} {det['score']:.2f}"
                cv2.putText(
                    img_cv, label_str, (bx1, max(by1 - 5, 0)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1,
                )
            cv2.imwrite(output_path, img_cv)
            log.info("Image annotée sauvegardée : %s", output_path)
        except ImportError:
            log.warning(
                "opencv-python non installé — annotation ignorée. "
                "pip install opencv-python pour l'activer."
            )

    log.info("%d détection(s) sur %s", len(detections), image_path)
    return detections


# ============================================================
# POINT D'ENTRÉE
# ============================================================
if __name__ == "__main__":
    #train(CFG)
    best_weights = Path(CFG.ckpt_dir) / "best.pt"
    export_onnx(
        cfg=CFG,
        weights_path=str(best_weights) if best_weights.exists() else None,
    )

    # ── Exemple d'inférence ONNX sur une image ─────────────────────────────
    # Décommentez et adaptez le chemin pour tester :
    #
    # COCO_CLASS_NAMES = [
    #     "person","bicycle","car","motorcycle","airplane","bus","train",
    #     "truck","boat","traffic light","fire hydrant","stop sign",
    #     "parking meter","bench","bird","cat","dog","horse","sheep","cow",
    #     "elephant","bear","zebra","giraffe","backpack","umbrella","handbag",
    #     "tie","suitcase","frisbee","skis","snowboard","sports ball","kite",
    #     "baseball bat","baseball glove","skateboard","surfboard",
    #     "tennis racket","bottle","wine glass","cup","fork","knife","spoon",
    #     "bowl","banana","apple","sandwich","orange","broccoli","carrot",
    #     "hot dog","pizza","donut","cake","chair","couch","potted plant",
    #     "bed","dining table","toilet","tv","laptop","mouse","remote",
    #     "keyboard","cell phone","microwave","oven","toaster","sink",
    #     "refrigerator","book","clock","vase","scissors","teddy bear",
    #     "hair drier","toothbrush",
    # ]
    #
    # detections = infer_onnx(
    #     image_path="image.jpg",
    #     onnx_path=CFG.onnx_path,
    #     cfg=CFG,
    #     class_names=COCO_CLASS_NAMES,
    #     output_path="image_annotated.jpg",
    # )
    # print(detections)
